
export const FETCHING_DATA = 'FETCHING_DATA_CART_PAGE';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS_CART_PAGE';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE_CART_PAGE';
export const DELETE_DATA = 'DELETE_DATA_CART_PAGE';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS_CART_PAGE';
export const DELETE_DATA_FAILURE = 'DELETE_DATA_FAILURE_CART_PAGE';
export const REST_VALUE = 'RESET_VALUE_CART_PAGE';
export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST';
export const PAY_ORDER_REQUEST_SUCCESS = 'PAY_ORDER_REQUEST_SUCCESS';
export const PAY_ORDER_REQUEST_FAILURE = 'PAY_ORDER_REQUEST_FAILURE';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const ADD_ITEM_CART = 'ADD_ITEM_CART';
export const RESET_CART = 'RESET_CART';