
export const FETCHING_DATA = 'FETCHING_DATA_CATEGORY_PAGE';
export const FETCHING_DATA_SEARCH = 'FETCHING_DATA_CATEGORY_PAGE_SEARCH';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS_CATEGORY_PAGE';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE_CATEGORY_PAGE';

export const FETCHING_NEXT = 'FETCHING_NEXT';