
export const FETCHING_DATA = 'FETCHING_DATA_DETAIL_PAGE';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS_DETAIL_PAGE';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE_DETAIL_PAGE';
export const FETCHING_DVT = 'FETCHING_DVT';
export const FETCHING_DVT_SUCCESS = 'FETCHING_DVT_SUCCESS';
export const FETCHING_DVT_FAILURE = 'FETCHING_DVT_FAILURE';