
export const FETCHING_DATA_LIKE = 'FETCHING_DATA_LIKE';
export const FETCHING_DATA_SUCCESS_LIKE = 'FETCHING_DATA_SUCCESS_LIKE';
export const FETCHING_DATA_FAILURE_LIKE = 'FETCHING_DATA_FAILURE_LIKE';
export const DELETE_DATA_LIKE = 'DELETE_DATA_LIKE';
export const DELETE_DATA_SUCCESS_LIKE = 'DELETE_DATA_SUCCESS_LIKE';
export const DELETE_DATA_FAILURE_LIKE = 'DELETE_DATA_FAILURE_LIKE';
export const ADD_ITEM_LIKE = 'ADD_ITEM_LIKE';