
export const FETCHING_DATA = 'FETCHING_DATA_MENU_PAGE';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS_MENU_PAGE';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE_MENU_PAGE';