export const FETCHING_DATA_ORDER = 'FETCHING_DATA_ORDER';
export const FETCHING_DATA_ORDER_SUCCESS = 'FETCHING_DATA_ORDER_SUCCESS';
export const FETCHING_DATA_ORDER_FAILURE = 'FETCHING_DATA_ORDER_FAILURE';
export const REFRESH_DATA_ORDER = 'REFRESH_DATA_ORDER';