
export const FETCHING_DATA = 'FETCHING_DATA_USER_PAGE';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS_USER_PAGE';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE_USER_PAGE';
export const REST_VALUE = 'RESET_VALUE_USER_PAGE';
export const FETCHING_USER_DATA = 'FETCHING_USER_DATA_USER_PAGE';
export const FETCHING_USER_DATA_SUCCESS = 'FETCHING_USER_DATA_SUCCESS_USER_PAGE';
export const FETCHING_USER_DATA_FAILURE = 'FETCHING_USER_DATA_FAILURE_USER_PAGE';

export const FETCHING_USER_DATA_REGISTER = 'FETCHING_USER_DATA_REGISTER';
export const FETCHING_USER_DATA_REGISTER_SUCCESS = 'FETCHING_USER_DATA_REGISTER_SUCCESS_USER_PAGE';
export const FETCHING_USER_DATA_REGISTER_FAILURE = 'FETCHING_USER_DATA_REGISTER_FAILURE_USER_PAGE';
export const LOGOUT_ACTION_PAGE = 'LOGOUT_ACTION_PAGE';
export const LOGOUT_ACTION_PAGE_SUCCESS = 'LOGOUT_ACTION_PAGE_SUCCESS';
export const REQUEST_FORGOT_PASSWORD = 'REQUEST_FORGOT_PASSWORD';
export const REQUEST_DELETE_USER_ADDRESS = 'REQUEST_DELETE_USER_ADDRESS';
export const REQUEST_ADD_USER_ADDRESS = 'REQUEST_ADD_USER_ADDRESS';

export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE';

export const FETCHING_REPORT_DATA = 'FETCHING_REPORT_DATA'
export const FETCHING_REPORT_SUCCESS = 'FETCHING_REPORT_SUCCESS'
export const FETCHING_REPORT_FAILURE = 'FETCHING_REPORT_FAILURE'

export const FETCHING_COMMISSION = 'FETCHING_COMMISSION'
export const FETCHING_COMMISSION_SUCCESS = 'FETCHING_COMMISSION_SUCCESS'
